### ISSUE TITLE
cfg_query subcommand can't query computed values

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#66]
The `compatible_applications` property of a station seems to be a value that's computed from the YAML config. But you can't query it even though it is listed as a property of a station.
```
$ python3 tools/hilbert.py cfg_query --configfile tests/data/Hilbert.yml -o Stations/testhost1/compatible_applications
ERROR  [hilbert.py:234]: Sorry cannot query 'Stations/testhost1/compatible_applications' yet!
Traceback (most recent call last):
  File "tools/hilbert.py", line 232, in cmd_query
    obj = cmd_list(parser, context, args, obj)
  File "tools/hilbert.py", line 203, in cmd_list
    return cfg.query(obj)
  File "/path/to/hilbert/hilbert-cli/hilbert_config/hilbert_cli_config.py", line 619, in query
    return d.query(t, _default)  # TODO: FIXME: avoid recursion...
  File "/path/to/hilbert/hilbert-cli/hilbert_config/hilbert_cli_config.py", line 619, in query
    return d.query(t, _default)  # TODO: FIXME: avoid recursion...
  File "/path/to/hilbert/hilbert-cli/hilbert_config/hilbert_cli_config.py", line 626, in query
    "Sorry cannot query '{0}' of {1}!".format(what, type(self))))
hilbert_cli_config.ConfigurationError: ERROR:: Sorry cannot query 'compatible_applications' of <class 'hilbert_cli_config.Station'>!
```
If I just query the whole data set for `testhost1`, the key `compatible_stations` is there, but it's just and empty list `[]` (didn't check if this is correct).

**Comment by malex984** [comment]
This issue should be fixed with commit https://github.com/hilbert/hilbert-cli/commit/d1a01e7203253525365ca6cbb185bf1b3191de33
